### ISSUE TITLE
Prefer governmentParty over country when both exist for a payment

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#259] opened 2015-11-16 11:27 UTC
Regarding https://github.com/NRGI/resource-projects-dataload/issues/28 

When a governmentReceipt exists, it is always related to the country. It is also related to a named organisation if one is given. 

This can lead to duplicates. We should update the query to only display government entities when both government entity and country are present as the payment recipient. 

I'm happy to take a first look at updating the query.

**Comment by timgdavies** [comment] 2015-11-18 17:33
I've been looking at [the query for GovernmentReceipts on a project page where this was an issue](https://github.com/NRGI/resourceprojects.org-frontend/blob/master/components/types/local_def__Project/queries/receipt.query) and have had a go at the following updated query:

```sparql
prefix rp: <http://resourceprojects.org/def/>
# We can't use the prefix 'skos' as lodspeakr will then put a prefix satement
# before the DEFINE statement, which is not allowed.
prefix skos_: <http://www.w3.org/2004/02/skos/core#>

# Country is actual recipient: can be either a country or an organisation

SELECT ?GovernmentReceipt ?paymentOrReceipt ?country ?country_name ?currency (replace(?amount,",","") as ?amount) ?date ?year ?type  WHERE {

        ?GovernmentReceipt rp:relatedProject <http://resourceprojects.org/project/PH/apma-l9nepr>.
        ?GovernmentReceipt a rp:GovernmentReceipt .
        ?GovernmentReceipt a ?paymentOrReceipt .        

       OPTIONAL {
        ?GovernmentReceipt rp:payee ?countryParty .
        ?countryParty a rp:Country .
        ?countryParty skos_:prefLabel ?countryParty_name.
       }
       OPTIONAL {
        ?GovernmentReceipt rp:payee ?govParty .
        ?govParty a rp:GovernmentParty.
        ?govParty skos_:prefLabel ?govParty_name.
       }

       ## This should be renamed payee, but for now we stick with country to avoid reworking the html templates
       BIND(IF(bound(?govParty),?govParty,?countryParty) as ?country)
       BIND(IF(bound(?govParty),?govParty_name,?countryParty_name) as ?country_name)

        OPTIONAL { ?GovernmentReceipt rp:currency ?currency }
        OPTIONAL { ?GovernmentReceipt rp:value ?amount } 
        OPTIONAL { ?GovernmentReceipt rp:date ?date } 
        OPTIONAL { ?GovernmentReceipt rp:year ?year }
        OPTIONAL { ?GovernmentReceipt rp:paymentType ?paymentType .
               ?paymentType skos_:prefLabel ?type }

}
GROUP BY ?GovernmentReceipt
ORDER BY ?date ?year
```

The key change here is that we look for both a government party and a country, and then bind if both are found, bind the government party to the ```country``` and ```country_name``` variables (to avoid having to rework the html templates for now). 

@caprenter could you have a look and see if you think this works. I've only tested against a few projects.

I think this query update would also need to be added to quite a few other places where we deal with payments to cut back on the duplications.

**Comment by caprenter** [comment] 2015-11-19 11:07
I've looked at this and not sure it does what you intend. 
The fix is now on a branch.

The page with the problem is here:
http://alpha.resourceprojects.org/project/PH/apma-ku0f7d.html

It would be good (perhaps) to write a test that tells us what should and should not be showing on that page. We may need to talk...

**Comment by caprenter** [comment] 2015-11-19 11:14
This fix also breaks tests by killing off the data in another projects payment table.

**Comment by caprenter** [comment] 2015-11-19 11:26
umm - however, this could be problem with the fixture data, and not the fix itself...

**Comment by timgdavies** [comment] 2015-11-19 11:43
We need to add rp:Payer to the government receipts query.

**Comment by caprenter** [comment] 2015-11-20 11:25
This is merged. It passes tests and looks good locally - so I'm closing this

**Closed by caprenter** 2015-11-20 11:25 UTC
Labels: 3 - Done, bug
