### ISSUE TITLE
sort function not working in large tables

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#190] opened 2015-10-21 09:47 UTC
Lists that are larger than table to display them, such as Mexico project list, won`t sort the full data, only what they display. Hence no way to display project names that start with second half of alphabet, even when reversing project alphabetical order, or using other variable to sort.

**Comment by caprenter** [comment] 2015-10-22 09:00
Assigning to you ben for now - but push back if you need to

**Comment by Bjwebb** [comment] 2015-10-22 09:31
Closing as a duplicate of https://github.com/NRGI/resourceprojects.org-frontend/issues/83

**Closed by Bjwebb** 2015-10-22 09:31 UTC
Labels: duplicate
